[project]
name = "hiho-cli-audio"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.11.7",
    "pynput>=1.8.1",
    "pyperclip>=1.9.0",
    "pyyaml>=6.0.2",
    "sounddevice>=0.5.2",
    "typer>=0.16.0",
]
